### ISSUE TITLE
NoWrap bug

### ISSUE THREAD

**Issue by ardera** [SquidDev-CC/Howl#13]
There's a bug in the Combiner: line 64 should be "if not noWrap then" (same with line 66)

**Comment by SquidDev** [comment]
Lines [82 and 84](https://github.com/SquidDev-CC/Howl/blob/master/depends/Combiner.lua#L82-84) should be (Sorry). Line 63 is correct though: If `noWrap` is true then we should use normal functions.

**Comment by ardera** [comment]
Yes, seems like I got confused with the line numbers.

Off-topic: I have an idea for finalizers (if the program errors, let the finalizer close all file handles etc) and a feature to convert program line numbers into module line numbers. 
What do you think? (Actually, I'm almost done with the line number thing)

**Comment by SquidDev** [comment]
That is a point, I never close handles when errors occur. Both sound very interesting. The only solution I could find to line numbers was something like [this](http://code.matthewwild.co.uk/squish/file/2322f7932064/debug/squish.debug.lua) but that won't work with separate files. Part of the reason I wrote the [bootstrap](https://github.com/SquidDev-CC/Howl/blob/master/depends/Bootstrap.lua) file was to cope with that, but again, this isn't ideal.

I'm working on closing #5 at the moment, then I'll push another pre-release. If you could get together a pull request in the next couple of days I'll include it in that.

Thanks :smile:
