### ISSUE TITLE
WebBuild

### ISSUE THREAD

**Issue by SquidDev** [SquidDev-CC/Howl#17]
@ardera Suggested:

>> **ardera, on 07 January 2015 - 06:43 PM, said:**
     What about adding a task which builds a program from a GitHub repository? I think luarocks has this    option too.
    something like this:
    `howl webbuild SquidDev-CC/Howl`
    It would fetch the repository to a cache directory, and try to run the build task.

> What do you think?

>  Yeah, I don't see why not. I mostly use Grin-Get or pastebin for releases, this is possible. I think a task    should be defined in the HowlFile though. Like `:Default` but `:WebBuild`. Development is different to     deployment, so it should be different commands.

The idea would be `Howl WebBuild SquidDev-CC/Howl` would clone the Howl repo, and run the `:WebBuild` task.

I'm wondering if we could use an emulated file system such as [Compilr](/SquidDev-CC/Howl/blob/master/files/Compilr.lua) so we don't end up spamming the file system. Anything that the task `:Produces` would be saved to the filesystem.

**Comment by SquidDev** [comment]
I've done some work on this on the [feature/webbuild](https://github.com/SquidDev-CC/Howl/tree/feature/webbuild) branch. This currently:

 - Allows you to choose what repo, branch (or tag or sha) to use, and what task to run.
 - We then download all the files and store them in memory.
 - We manually run Howl with an emulated filesystem.

I'm going to add an option to choose the Howl executable to run. The only issue is the Howlfile must be in the root of the project.

**Comment by ardera** [comment]
Maybe one could set the howl version in the howlfile. And it should be possible to let the howlfile decide if the included howl from the project is used (path is set by the howlfile too), if the running howl is used or if howl with version X should be used.

**Comment by SquidDev** [comment]
I'm slightly confused: You are saying the HowlFile should specify which version of Howl to use. The options being:
 - The current version (default)
 - Custom path
 - Version whatever

At the moment WebBuild is a stand alone script. I'm not sure how best to integrate it with the existing Howl code. I don't really understand the point of setting the version of Howl though? Or am I just missing the point?

**Comment by ardera** [comment]
Maybe an old program depends on a specific version (in this case old) of howl. (For example, if a feature is removed/modified and older programs don't work with the new modification, or without this feature.)

**Comment by SquidDev** [comment]
Deleted the old code and added as a separate project on the [webbuild](https://github.com/SquidDev-CC/Howl/tree/web-build) branch.

It allows specifying a `.howl` file which will store various settings:

```lua
{
 howl = "http://pastebin.com/raw.php?i=uHRTm9hp", -- URL or file in repo.
}
```
