### ISSUE TITLE
Replacing is broken

### ISSUE THREAD

**Issue by ardera** [SquidDev-CC/Howl#18]
build a project with :LineMapper() and :Traceback(), open the built file and look for the line the lineToModule table and the modulestarts table is declared.
it says: 
lineToModule = setmetatable(nil, ...
modulestarts = nil

The TraceMapper (Traceback + Linemapper = TraceMapper) errors and can't call the finalize function, too.

**Comment by SquidDev** [comment]
Fixed. That was a really stupid mistake.
