### ISSUE TITLE
Dependencies:Resource()

### ISSUE THREAD

**Issue by ardera** [SquidDev-CC/Howl#19]
What about adding a `Dependencies:Resource(f)` function that includes the resource as a multilinestring instead of code?

**Comment by SquidDev** [comment]
So:
```lua
 Dependencies::Resource "myfile"
  :Name "something"
```
Would produce:
```lua
local something = [[contents of my file]]
```

This should be pretty easy to implement. 

However should [Verify](https://github.com/SquidDev-CC/Howl/blob/master/depends/modules/Verify.lua) still be called? I wonder if it should be possible to override verification (disable/enable for individual files). The same applies for other file hooks, as they are not files but resources, so line mapping is not really needed.

I presume this would be useful for embedded images and other similar sources?

**Comment by ardera** [comment]
Exactly, this would be, as you said, useful for including images (etc)
Every File object should have a boolean called doVerification. By default, every module/mainmodule is verificated and every resource not, but I think one should have the ability to toggle the verification for every file object.

**Comment by SquidDev** [comment]
See #20
