### ISSUE TITLE
Minifying breaks Linemapping

### ISSUE THREAD

**Issue by ardera** [SquidDev-CC/Howl#21]
If you minify a program that has the linemapping feature enabled, the linenumbers used by the linemapper will be broken.

**Comment by SquidDev** [comment]
But line mappings won't be accurate anyway seeing as the minifier removes most whitespace. The only useful information you will get is the file it errored in.

**Comment by ardera** [comment]
Thats right. I think the best option would be to cut the linemapper in a minified program. If you find a bug, you simply reproduce it in an unminified version.

Also, in the linemapper, if the line you give as an index to the lineToModule table is too far away from the next existing entry, the linemapper will crash with an stackoverflow, since the __index metamethod is recursive. (I heard if you use tailcalls, the stack won't grow. This is false it seems)

The best fix would be to add an entry every 100 indexes or something, so the __index metamethod finds a value before the stack becomes to big. Do you understand what I mean?
