### ISSUE TITLE
Sometimes Minifying breaks code

### ISSUE THREAD

**Issue by ardera** [SquidDev-CC/Howl#23]
It breaks the code when a semicolon is used to determine an ambiguous syntax, it doesn't place a semicolon in the output. For example:

`something(a, b); (c or d)(x, y)` becomes `something(a, b)(c or d)(x, y)` in the minified code, which will result in an attempt to call nil

**Comment by SquidDev** [comment]
This will involve [backporting this](https://github.com/SquidDev/LuaCompilerProject/blob/master/metalua/compiler/source/compile.mlua#L114-L148). TBH I'm probably just going to use LuaCP as Howl's minifier but that can wait. I'll try to fix today.

**Comment by jaredallard** [comment]
:+1: for a fix.

**Comment by SquidDev** [comment]
Guys I'm working on it...

**Comment by SquidDev** [comment]
Fine, have a release.
