### ISSUE TITLE
Modules using program varargs crash the program

### ISSUE THREAD

**Issue by ardera** [SquidDev-CC/Howl#24]
If you try to use bedrock for example as a module, the built program will crash because the function it's contained in has no varargs, but it tries to access varargs.

The fix is simple: just emit `local <modulename> = _W(function(...) <modulecontent> end)` instead of the old `local <modulename> = _W(function() <modulecontent> end)`

**Comment by jaredallard** [comment]
:+1: Perhaps make a PR? :)

**Comment by SquidDev** [comment]
I'll do it, I'm kinda busy ATM, sorry.

**Comment by ardera** [comment]
No need to make a pull request, it's just one line needing to be changed to fix this.
