### ISSUE TITLE
Crash report - Howl:5: table index expected, got nil

### ISSUE THREAD

**Issue by lupus590** [SquidDev-CC/Howl#30]
Installed via `pastebin run LYAxmSby get 703e2f46ce68c2ca158673ff0ec4208c/Howl.min.lua Howl`

Tried `pastebin run LYAxmSby get 703e2f46ce68c2ca158673ff0ec4208c/Howl.lua Howl` and that worked (well stopped after not finding a Howlfile, but that's my fault).

**Comment by SquidDev** [comment]
The minifier is renaming function arguments to be the same as upvalues:

```lua
local foo = {}
local function something(bar)
	print(foo)
end
```
gets minified to
```lua
local e={} local function t(e) print(e) end
```
