### ISSUE TITLE
Titanium Packager Support

### ISSUE THREAD

**Issue by hbomb79** [SquidDev-CC/Howl#33]
Link to [packager](https://gitlab.com/hbomb79/Titanium/blob/develop/bin/package.lua)

Let me know if you need me to explain what certain parts do, it isn't programmed in the cleanest way as you likely noticed.

The packager software will be changed between now and Titanium's full release, hopefully that won't cause problems when ensuring Howl uses the latest version of the packager.

The packager already handles minification, the advantage of it running in Howl would largely be it's dependency management.

**Comment by SquidDev** [comment]
@hbomb79 Do you have a fancy name for this packager? Or is it just "titanium packager"?

**Comment by hbomb79** [comment]
No, not really @SquidDev. I am open to suggestions, otherwise "Titanium Project Packager" or something similar will do.

Sorry for the late response.

**Comment by SquidDev** [comment]
I've added an initial version [here](https://gist.github.com/SquidDev/36c934148df4c625a179da1d5a27792c). 

#### Current issues:
 - Doesn't include titanium installer. This is trivial, just requires me adding a couple of options/validation for it
 - Doesn't exclude files from the VFS which are on the extract/class list.

#### Example syntax
@hbomb79 Thoughts on this?
```lua
plugins { { type = "gist", id = "36c934148df4c625a179da1d5a27792c" } }

Tasks:titanium "build" {
	sources = { include = { "example/*.lua", "example/*.td" } },
	extract = { include = { "example/ui } },
	startup = "example/main.lua",
	output = "build/build.lua",
	minify = true,
}
```
You can also write:
```
Tasks:titanium "build" (function(t)
	t.sources:include { "example/*.lua", "example/*.td" }
	t.extract:include = { "example/ui } },
	t.startup = "example/main.lua"
	t.output = "build/build.lua"
	t.minify = true
}
```
if it floats your boat.

**Comment by hbomb79** [comment]
Just so you know, it is `*.ti` not `*.td`.

Other than that, it looks fine. How do you assign class source? They must be loaded differently, including validating the class loaded correctly and preprocessing the class file.

**Comment by SquidDev** [comment]
Right. I think I've fixed all the bugs/implemented what needed doing. 

I've tested that Plexus compiles, though running breaks as everything is one folder too deep. The Howl file I'm using
```lua
plugins { { type = "gist", id = "36c934148df4c625a179da1d5a27792c" } }

Tasks:titanium "build" {
        sources = { include = { "Plexus" } },
        classes = { include = { "Plexus/lib/classes" } },
        startup = "Plexus/init.lua",
        output = "build/build.lua",
        minify = true,
        titaniumPath = "titanium.lua"
}
```
