### ISSUE TITLE
Gist task not working

### ISSUE THREAD

**Issue by MineRobber9000** [SquidDev-CC/Howl#39]
In my project, I have a task to upload to a gist. I set up the settings.lua file in .howl so that it had my github key in it. It still showed the "You have no github key" message.

My .howl/settings.lua looks like:

    {
        ["githubKey"]="redacted"
    }

**Comment by SquidDev** [comment]
Sorry for taking an age to get to this. Are you using Howl from the Gist, or the current repository? If it is the former, you'll need to use `.howl.settings.lua` instead.

**Comment by MineRobber9000** [comment]
I was using the howl from the gist, thanks for clarifying.
